spawner-percent: 0.6

# Основные настройки плагина
drop-chance: 0.75
show-action-bar-messages: true
player-death-drop-percentage: 0.07

# Множители для зачарования "Удача"
fortune-multipliers:
  1: 1.25  # Удача I - увеличивает выпадение монет на 25%
  2: 1.5   # Удача II - увеличивает выпадение монет на 50%
  3: 1.75  # Удача III - увеличивает выпадение монет на 75%

# Множители для зачарования "Добыча"
looting-multipliers:
  1: 1.25  # Добыча I - увеличивает выпадение монет на 25%
  2: 1.5   # Добыча II - увеличивает выпадение монет на 50%
  3: 1.75  # Добыча III - увеличивает выпадение монет на 75%