# Коэффициент выпадения монет из мобов из спавнера
spawner-percent: 0.6

# Основные настройки плагина
drop-chance: 0.75 # Вероятность выпадения монет при добыче блоков и убийстве мобов
show-action-bar-messages: true # Показывать сообщения при подборе монет в Action Bar
player-death-drop-percentage: 0.07 # Коэффициент выпадения монет из убитого игрока

# Сообщения о множителях
show-fortune-multiplier-messages: false
show-looting-multiplier-messages: false

# Множители для зачарования "Удача"
fortune-multipliers:
  1: 1.25  # Удача I - увеличивает выпадение монет на 25%
  2: 1.5   # Удача II - увеличивает выпадение монет на 50%
  3: 1.75  # Удача III - увеличивает выпадение монет на 75%

# Множители для зачарования "Добыча"
looting-multipliers:
  1: 1.25  # Добыча I - увеличивает выпадение монет на 25%
  2: 1.5   # Добыча II - увеличивает выпадение монет на 50%
  3: 1.75  # Добыча III - увеличивает выпадение монет на 75%